---
- hosts: gitlab_runner:!default
  vars:
    ansible_ssh_user: "{{ sudo_users |  map(attribute='username') | random }}"
  tasks:
    - name: Unregister Gitlab runners.
      community.docker.docker_container_exec:
        container: '{{ gitlab_runner_container_name }}'
        command: /bin/bash -c "gitlab-runner unregister --all-runners"
      become: true
...